modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Zergatul/freecam/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/freecam-by-zergatul"
logoFile="icon.png"
authors="${mod_authors}"
description='''
Use F6 to toggle FreeCam, or change key bind in the settings.
Open Mods menu, select FreeCam, click Config to access mod settings.
Alternatively you can type .freecam in chat to open mod settings.
'''

[[dependencies.${mod_id}]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"