import java.nio.file.Paths
import org.apache.tools.ant.taskdefs.condition.Os

buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/maven' }
        mavenCentral()
    }
}

plugins {
    id 'fabric-loom' version '1.13-SNAPSHOT'
    id 'maven-publish'
}

loom {
    mixin {
        useLegacyMixinAp = true
    }
}

def commonProperties = new Properties()
file('../common/gradle.properties').withInputStream { commonProperties.load(it) }
ext.mod_version = commonProperties['mod_version']

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

repositories {
}

sourceSets {
    main {
        java {
            srcDir '../common/mod/java'
            srcDir '../common/mixin-plugin/java'
        }
        resources {
            srcDir '../common/mod/resources'
            srcDir 'src/generated/resources'
        }
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Uncomment the following line to enable the deprecated Fabric API modules.
    // These are included in the Fabric API production distribution and allow you to update your mod to the latest modules at a later more convenient time.

    // modImplementation "net.fabricmc.fabric-api:fabric-api-deprecated:${project.fabric_version}"
    annotationProcessor files('../annotation-processor/build/libs/annotation-processor.jar')
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    //withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}"}
    }

    exclude("com/terraformersmc/**")
}

tasks.register('buildAnnotationProcessor', {
    doFirst {
        def annotationProcessorJar = file('../annotation-processor/build/libs/annotation-processor.jar')
        if (!annotationProcessorJar.exists()) {
            println 'Annotation processor JAR not found. Building annotation processor...'
            def buildResult = exec {
                def gradlew = Os.isFamily(Os.FAMILY_WINDOWS) ? 'gradlew.bat' : 'gradlew'
                commandLine "../annotation-processor/$gradlew", '-p', '../annotation-processor', 'build'
            }
            if (buildResult.exitValue != 0) {
                throw new GradleException('Failed to build the annotation processor project.')
            }
        }
    }
})

tasks.withType(JavaCompile).configureEach {
    dependsOn('buildAnnotationProcessor')
}

remapJar {
    afterEvaluate {
        archiveFileName = "$archives_base_name-$mod_version-fabric-${minecraft_version}.jar"
    }
}