plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

def commonProperties = new Properties()
file('../common/gradle.properties').withInputStream { commonProperties.load(it) }
ext.mod_version = commonProperties['mod_version']

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

sourceSets {
    main {
        java {
            srcDir '../common/mod/java'
            srcDir '../common/mixin-plugin/java'
        }
        resources {
            srcDir '../common/mod/resources'
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    //withSourcesJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}"}
    }

    exclude("com/terraformersmc/**")
}

tasks.jar {
    archiveFileName.set("${base.archivesName.get()}-${project.mod_version}-fabric-${project.minecraft_version}.jar")
}