plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

def commonProperties = new Properties()
file('../common/gradle.properties').withInputStream { commonProperties.load(it) }
def modVersion = commonProperties['mod_version']
def mixinsConfigOriginal = 'freecam.mixins.json'
def mixinsConfigForge = 'freecam.forge.mixins.json'
def generatedMixinsConfigDir = layout.buildDirectory.dir('generated/resources/forgeMixins')

version = modVersion
group = mod_group_id

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

minecraft {
    runs {
        client {
            workingDir = layout.projectDirectory.dir('run')
            args "-mixin.config=${mixinsConfigForge}"

            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

tasks.register('generateForgeMixinsConfig', Copy) {
    from('../common/mod/resources') {
        include mixinsConfigOriginal
        filter { String line -> line.replace("JAVA_25", "JAVA_21") }
        rename { mixinsConfigForge }
    }
    into generatedMixinsConfigDir
}

sourceSets {
    main {
        java {
            srcDir '../common/mod/java'
            srcDir '../common/mixin-plugin/java'
        }
        resources {
            srcDir '../common/mod/resources'
            exclude mixinsConfigOriginal
            srcDir generatedMixinsConfigDir
            srcDir 'src/generated/resources'
        }
    }
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
}

tasks.named('processResources', ProcessResources) {
    dependsOn tasks.named('generateForgeMixinsConfig')

    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: modVersion,
            mod_authors: mod_authors,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar) {
    archiveFileName = "zergatul.freecam-$modVersion-forge-${minecraft_version}.jar"

    manifest {
        attributes([
            'MixinConfigs': mixinsConfigForge
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea.module { downloadJavadoc = downloadSources = true }