net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.1
minecraft_version_range=[26.1,27.1)
forge_version=62.0.1
forge_version_range=[62,)
loader_version_range=[62,)

mod_id=zergatulfreecam
mod_name=FreeCam by Zergatul
mod_license=MIT License
mod_group_id=com.zergatul.freecam
mod_authors=Zergatul