name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 25

      - name: Build
        run: |
          cd universal
          ./gradlew universalJar -Ploaders=fabric

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: universal
          path: universal/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error