name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 21

      - name: Build Fabric
        run: |
          cd fabric
          ./gradlew build

      - name: Build Forge
        run: |
          cd forge
          ./gradlew build

      - name: Build NeoForge
        run: |
          cd neoforge
          ./gradlew build

      - name: Upload fabric artifacts
        uses: actions/upload-artifact@main
        with:
          name: fabric
          path: fabric/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error

      - name: Upload forge artifacts
        uses: actions/upload-artifact@main
        with:
          name: forge
          path: forge/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error

      - name: Upload neoforge artifacts
        uses: actions/upload-artifact@main
        with:
          name: neoforge
          path: neoforge/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error