name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 25

      - name: Build Fabric
        run: |
          cd fabric
          chmod +x ./gradlew
          ./gradlew build
          cd ..

      - name: Build Forge
        run: |
          cd forge
          chmod +x ./gradlew
          ./gradlew build
          cd ..

      - name: Build NeoForge
        run: |
          cd neoforge
          chmod +x ./gradlew
          ./gradlew build
          cd ..

      - name: Upload fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fabric
          path: fabric/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error

      - name: Upload forge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: forge
          path: forge/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error

      - name: Upload neoforge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neoforge
          path: neoforge/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error